### PR TITLE
Fix Traditional Chinese resource directory name.

### PR DESCRIPTION
**Pull request by eric100lin**
Update the resource directory of Traditional Chinese according to https://github.com/maxrave-dev/SimpMusic/commit/273c65e214109030938331d9ae18b4e6ce00852d.

### CODE REVIEW

**Comment by maxrave-dev** [comment]
No need to do this bro, zh-rTW still works with values directory

**Comment by eric100lin** [comment]
This is required for the app to get Traditional Chinese resources.

**Comment by maxrave-dev** [comment]
No needed, check out latest nightly build

**Comment by eric100lin** [comment]
This configuration is necessary for the app to access Traditional Chinese resources. You can test this using per-app language settings. Ensure the resource directory name aligns with the resourceConfigurations specified in your build.gradle.kts file. Additionally, I'm not seeing Traditional Chinese support in the nightly build.

**Pull request closed without merging**
