### PR TITLE
Update strings.xml

### PR DESCRIPTION
**Pull request by Mickael81**
Improved French translation.

### CODE REVIEW

**Comment by maxrave-dev** [comment]
Thanks @Mickael81

**Comment by Iliano101** [comment]
@Mickael81 
Are you sure about this ? Playlist is an anglicism.

**Comment by Mickael81** [comment]
> @Mickael81 Are you sure about this ? Playlist is an anglicism.
Screenshot_20241128_095839
Screenshot_20241128_095959
You are right "playlist" is indeed an anglicism. However, the term is much more used and evocative in France than "liste de lecture".
As you can see on the attached screenshots, YouTube Music and Spotify do indeed speak of "playlist" in the translation of their application into French.

**Comment by Iliano101** [comment]
@Mickael81 
Lol well in French - QC it says "Liste de lecture" so that's why I found that strange. Québec seems to be much more protective of the language.

**Comment by Iliano101** [comment]
Maybe we could get a French - CA version of the strings ?

**Pull request merged**
