### PR TITLE
(Fixed #200) "Crashing on specific song"

### LINKED ISSUE #200: Crashing on specific song
**Describe the bug**
A couple seconds into playing "Air I Breathe" by Sondae, the app crashes with an error message

**To Reproduce**
1. Search for the song above
2. Hit play

**Expected behavior**
The song should play without errors

**Video**
https://github.com/maxrave-dev/SimpMusic/assets/77121604/be6184d5-cf96-4c2d-9059-423e2ff0b32f

**Log (Error Details)**

Build version: 0.1.7 
Current date: 2023-12-23 20:08:30 
Device: Google Pixel 7 
OS version: Android 14 (SDK 34) 
 
Stack trace:  
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.util.Objects.checkIndex(Objects.java:359)
	at java.util.ArrayList.get(ArrayList.java:434)
	at com.maxrave.simpmusic.viewModel.SharedViewModel.getActiveLyrics(SharedViewModel.kt:860)
	at com.maxrave.simpmusic.ui.fragment.player.NowPlayingFragment$onViewCreated$10$1$job5$1$1.emit(NowPlayingFragment.kt:583)
	at com.maxrave.simpmusic.ui.fragment.player.NowPlayingFragment$onViewCreated$10$1$job5$1$1.emit(NowPlayingFragment.kt:570)
	at kotlinx.coroutines.flow.StateFlowImpl.collect(StateFlow.kt:396)
	at kotlinx.coroutines.flow.StateFlowImpl$collect$1.invokeSuspend(Unknown Source:15)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:68)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:260)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at com.maxrave.simpmusic.viewModel.SharedViewModel.sponsorBlockEnabled(SharedViewModel.kt:1081)
	at com.maxrave.simpmusic.ui.MainActivity$onCreate$11$job1$1$1.emit(MainActivity.kt:592)
	at com.maxrave.simpmusic.ui.MainActivity$onCreate$11$job1$1$1.emit(MainActivity.kt:590)
	at kotlinx.coroutines.flow.StateFlowImpl.collect(StateFlow.kt:396)
	at kotlinx.coroutines.flow.StateFlowImpl$collect$1.invokeSuspend(Unknown Source:15)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:68)
	at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:245)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:163)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:474)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:508)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:497)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:368)
	at kotlinx.coroutines.flow.StateFlowSlot.makePending(StateFlow.kt:284)
	at kotlinx.coroutines.flow.StateFlowImpl.updateState(StateFlow.kt:349)
	at kotlinx.coroutines.flow.StateFlowImpl.setValue(StateFlow.kt:316)
	at com.maxrave.simpmusic.service.SimpleMediaServiceHandler.startProgressUpdate(SimpleMediaServiceHandler.kt:397)
	at com.maxrave.simpmusic.service.SimpleMediaServiceHandler.access$startProgressUpdate(SimpleMediaServiceHandler.kt:42)
	at com.maxrave.simpmusic.service.SimpleMediaServiceHandler$startProgressUpdate$1.invokeSuspend(Unknown Source:14)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:235)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:168)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:474)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:508)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:497)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched(CancellableContinuationImpl.kt:595)
	at kotlinx.coroutines.android.HandlerContext$scheduleResumeAfterDelay$$inlined$Runnable$1.run(Runnable.kt:19)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8470)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@a07af69, Dispatchers.Main.immediate]

User actions: 
2023-12-23 20:07:48: MainActivity created
2023-12-23 20:07:49: MainActivity resumed

### PR DESCRIPTION
**Pull request by the-nid**
Added check for `lyricsFormat` list size to avoid the out of bounds exception

### CODE REVIEW

**Comment by Sumit09-maker** [comment]
Bro still facing the problem.

**Comment by Sumit09-maker** [comment]
Bro when we will get the fixed apk?

**Comment by maxrave-dev** [comment]
I will check out soon, too busy in final year school :(

**Review by maxrave-dev — COMMENTED** [review]
Add an empty list checker for lyricsFormat to fix this.

**Pull request closed without merging**
