### PR TITLE
Create strings.xml

### PR DESCRIPTION
**Pull request by WaldiSt**
Please add translation into Polish
Thanks

### CODE REVIEW

**Comment by maxrave-dev** [comment]
I will merge this into next build. Thanks for support me

**Comment by maxrave-dev** [comment]
@WaldiSt please transalate latest string.xml. In your merge, your translated file is missing too much string

**Comment by WaldiSt** [comment]
... and the Polish language is still missing ...

**Comment by maxrave-dev** [comment]
> please translate the latest string.xml. In your merge, your translated file is missing too much string

Please translate the latest string.xml. In your merge, your translated file is missing too much string :(

**Pull request merged**
